### ISSUE TITLE
stuck on restart

### ISSUE THREAD

**Issue by sakoula** [Stane1983/OpenCore_OptiPlex_5080#5]
Hi there and happy new year!

I am using an 5080 with Ventura and used your repository as a base. My problem is that the computer **canoot** restart and it stucks. When I shutdown it there is no problem. Is this something that you have seen? Thanks!!!!

**Comment by id-001** [comment]
Try this patch https://www.tonymacx86.com/threads/cant-restart-dell-precision-3440.317427/#post-2316870

**Comment by sakoula** [comment]
thanks a lot!!!!!
